apiVersion: v1
kind: Service
metadata:
  name: tilt-quarkus-demo-srv
  labels:
    app.kubernetes.io/name: tilt-quarkus-demo-srv
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: tilt-quarkus-demo
